<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<?php if ($block->isEnabled()) : ?>
    <div class="g-recaptcha
        <?php if ($block->isCompact()) : ?>
            g-recaptcha-compact
        <?php endif ?>">
     </div>
    <script type="text/x-magento-init">
        {".g-recaptcha": {"faonni/recaptcha": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>}}
    </script>
<?php endif ?>
