<?php
/**
 * Copyright © 2011-2018 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * 
 * See COPYING.txt for license details.
 */
?>
<?php if ($block->isEnabled()) : ?>
	<div class="g-recaptcha<?php if ($block->isCompact()): ?> g-recaptcha-compact<?php endif ?>"></div>
	<script type="text/x-magento-init">
		{".g-recaptcha": {"faonni/recaptcha": <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>}}
	</script>
<?php endif ?>
