<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<?php if ($block->isEnabled()) : ?>
    <div class="admin__field g-recaptcha
        <?php if ($block->isCompact()) : ?>
            g-recaptcha-compact
        <?php endif ?>"
        data-mage-init='{"faonni/recaptcha": <?= $block->escapeHtml($block->getJsonConfig()) ?>}'>
    </div>
<?php endif ?>
