<?php
/**
 * Copyright © 2011-2017 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * 
 * See COPYING.txt for license details.
 */
?>
<?php if ($block->isEnabled()) : ?>
<div class="admin__field g-recaptcha<?php if ($block->getSize() == 'compact'): ?> g-recaptcha-compact<?php endif ?>" data-theme="<?php echo $block->getTheme() ?>" data-type="<?php echo $block->getType() ?>" data-size="<?php echo $block->getSize() ?>" data-sitekey="<?php echo $block->getSiteKey() ?>"></div>
<?php endif ?>
