<?php
/**
 * Copyright © 2011-2018 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 *
 * See COPYING.txt for license details.
 */
?>
<?php if ($block->isEnabled()) : ?>
    <div class="admin__field g-recaptcha
        <?php if ($block->isCompact()) : ?>
            g-recaptcha-compact
        <?php endif ?>"
        data-mage-init='{"faonni/recaptcha": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>}'>
    </div>
<?php endif ?>
